services:
  mongodb:
    image: mongodb/mongodb-atlas-local:8.0.3-20250506T093411Z
    ports:
      - "27017:27017"
    volumes:
      - mongodb-data:/data/db
      - mongodb-config:/data/configdb
    healthcheck:
      test: ["CMD-SHELL", "mongosh --eval \"db.adminCommand({ ping: 1 })\""]
      interval: 10s
      timeout: 5s
      retries: 5

  app:
    image: mcr.microsoft.com/devcontainers/python:1-3.13-bookworm
    network_mode: service:mongodb
    volumes:
      - ..:/workspaces/FARM-Intro:cached
    command: sleep infinity
    depends_on:
      mongodb:
        condition: service_healthy

volumes:
  mongodb-data:
  mongodb-config:
