---
apiVersion: apps/v1
kind: Deployment
metadata:
  name: farm-intro-backend
  labels:
    app: farm-intro-backend
spec:
  replicas: 1
  selector:
    matchLabels:
      app: farm-intro-backend

  template:
    metadata:
      labels:
        app: farm-intro-backend
    spec:
      containers:
      - name: farm-intro
        command:
        - python3
        - main.py
        env:
        - name: DB_URL
          valueFrom:
            secretKeyRef:
              name: mdb-admin-my-user
              key: connectionString.standard
        - name: DB_NAME
          value: 'admin'
        image: quay.io/mongodb/farm-intro-backend:0.1
        imagePullPolicy: Always
        ports:
        - containerPort: 8000

      dnsPolicy: ClusterFirst
      restartPolicy: Always
      serviceAccount: default
      serviceAccountName: default
      terminationGracePeriodSeconds: 30

---
apiVersion: v1
kind: Service
metadata:
  labels:
    app: farm-intro-backend
  name: farm-intro-backend
spec:
  ipFamilies:
  - IPv4
  ipFamilyPolicy: SingleStack
  ports:
  - port: 8000
    protocol: TCP
    targetPort: 8000
  selector:
    app: farm-intro-backend
  sessionAffinity: None
  type: ClusterIP
